"""Rooms, Bookings, Users added

Revision ID: b8d69b9aee78
Revises: ac2839cb1bf9
Create Date: 2025-02-26 12:58:23.923293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d69b9aee78'
down_revision: Union[str, None] = 'ac2839cb1bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
